name: 'dynamic_pricing'
version: '1.0.0'
config-version: 2

profile: 'dynamic_pricing'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dynamic_pricing:
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
